version: '3.7'

services:
  wekandb-dev:
    image: mongo:6
    container_name: wekan-dev-db
    restart: unless-stopped
    command: mongod --oplogSize 128
    networks:
      - wekan-dev-tier
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/wekan-db:/data/db
      - ./volumes/wekan-db-dump:/dump

  wekan-dev:
    container_name: wekan-dev-app
    restart: always
    networks:
      - wekan-dev-tier
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - MONGO_URL=mongodb://wekandb-dev:27017/wekan
      - ROOT_URL=http://localhost:3000
      - WITH_API=true
      - DEBUG=true
      - RICHER_CARD_COMMENT_EDITOR=true
      - BROWSER_POLICY_ENABLED=true
      - WRITABLE_PATH=/data

      # Enable the OAuth2 connection
      - OAUTH2_ENABLED=true
      - OAUTH2_LOGIN_STYLE=popup
      # GitLab as authentication server:
      # - OAUTH2_CLIENT_ID=
      # - OAUTH2_SECRET=
      # - OAUTH2_SERVER_URL=https://serv22194.iis.sinica.edu.tw
      # - OAUTH2_REQUEST_PERMISSIONS=openid profile email
      - OAUTH2_CLIENT_ID=wekan
      - OAUTH2_SECRET=123456
      - OAUTH2_SERVER_URL=http://172.27.251.76:8080
      # - OAUTH2_AUTH_ENDPOINT=/oauth2/authorize
      - OAUTH2_AUTH_ENDPOINT=/login
      - OAUTH2_TOKEN_ENDPOINT=/oauth2/token
      - OAUTH2_USERINFO_ENDPOINT=/userinfo
      - OAUTH2_REQUEST_PERMISSIONS=openid profile email
      - OAUTH2_ID_MAP=sub
      - OAUTH2_USERNAME_MAP=sub
      - OAUTH2_FULLNAME_MAP=sub
      - OAUTH2_EMAIL_MAP=email
      # - OAUTH2_EMAIL_MAP=sub
    depends_on:
      - wekandb-dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/data:/data
      - ../client:/home/wekan/app/client
      - ../models:/home/wekan/app/models
      - ../config:/home/wekan/app/config
      - ../imports:/home/wekan/app/imports
      - ../server:/home/wekan/app/server
      - ../public:/home/wekan/app/public

networks:
  wekan-dev-tier:
    driver: bridge
